//
// Created by mqjyl on 2020/9/13.
//

#ifndef ALGORITHM_PATTERN_CODE_ALTERNATEPRINTER_H
#define ALGORITHM_PATTERN_CODE_ALTERNATEPRINTER_H


class AlternatePrinter {

};


#endif //ALGORITHM_PATTERN_CODE_ALTERNATEPRINTER_H
